# Generated by Django 4.0.4 on 2023-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodClassification',
            fields=[
                ('idfoodclassification', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('caloria', models.FloatField()),
                ('proteina', models.FloatField()),
                ('grasa', models.FloatField()),
                ('fibra', models.FloatField()),
                ('carbohidratos', models.FloatField()),
            ],
            options={
                'db_table': 'foodclassification',
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('idprediccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_uuid', models.CharField(max_length=200)),
                ('idfoodclassification', models.IntegerField()),
            ],
            options={
                'db_table': 'prediccion',
            },
        ),
    ]
