# Generated by Django 4.0.4 on 2023-10-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_foodclassification_prediccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodclassification',
            name='caloria',
        ),
        migrations.RemoveField(
            model_name='foodclassification',
            name='carbohidratos',
        ),
        migrations.RemoveField(
            model_name='foodclassification',
            name='fibra',
        ),
        migrations.RemoveField(
            model_name='foodclassification',
            name='grasa',
        ),
        migrations.RemoveField(
            model_name='foodclassification',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='foodclassification',
            name='proteina',
        ),
        migrations.AddField(
            model_name='foodclassification',
            name='description',
            field=models.CharField(default='Default decripcion', max_length=255),
        ),
        migrations.AddField(
            model_name='foodclassification',
            name='name',
            field=models.CharField(default='Default name', max_length=50),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='url',
            field=models.CharField(default='Default url', max_length=255),
        ),
        migrations.AlterField(
            model_name='foodclassification',
            name='idfoodclassification',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='nombre',
            field=models.CharField(default='Default name', max_length=255),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='nombre_uuid',
            field=models.CharField(default='Default name', max_length=255),
        ),
    ]
